import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { TASK_CATEGORY_FILES } from '../constants.js';
import type { CorydoraConfig, TaskCategory, TaskRecord, TaskStore } from '../types/domain.js';

function statusMarker(task: TaskRecord): string {
  switch (task.status) {
    case 'done':
      return '[x]';
    case 'blocked':
      return '[-]';
    case 'manual':
      return '[!]';
    case 'leased':
    case 'applying':
    case 'validating':
      return '[/]';
    case 'deferred':
      return '[~]';
    default:
      return '[ ]';
  }
}

function renderCategoryDocument(category: TaskCategory, tasks: TaskRecord[]): string {
  const title = category.charAt(0).toUpperCase() + category.slice(1);
  const lines = [
    `# ${title}`,
    '',
    'Generated by Corydora from `.corydora/state/tasks.json`.',
    '',
    '## Tasks',
    '',
  ];

  for (const task of tasks) {
    lines.push(
      `- ${statusMarker(task)} ${task.title} (\`${task.file}\`) <!-- corydora:id=${task.id} risk=${task.risk} severity=${task.severity} -->`,
    );
    lines.push(`  - Why: ${task.rationale}`);
    lines.push(`  - Validate: ${task.validation}`);
    if (task.lastError) {
      lines.push(`  - Last error: ${task.lastError}`);
    }
    if (task.validationResult) {
      lines.push(
        `  - Validation: ${task.validationResult.status} (${task.validationResult.summary})`,
      );
    }
  }

  if (tasks.length === 0) {
    lines.push('- No tasks queued.');
  }

  lines.push('');
  return lines.join('\n');
}

export async function renderTaskQueues(
  projectRoot: string,
  config: CorydoraConfig,
  store: TaskStore,
): Promise<void> {
  for (const [category, fileName] of Object.entries(TASK_CATEGORY_FILES) as Array<
    [TaskCategory, string]
  >) {
    const tasks = store.tasks
      .filter((task) => task.category === category)
      .filter((task) => config.todo.renderCompletedTasks || task.status !== 'done')
      .sort((left, right) => left.createdAt.localeCompare(right.createdAt));
    const document = renderCategoryDocument(category, tasks);
    await writeFile(
      resolve(projectRoot, config.paths.corydoraDir, fileName),
      `${document}\n`,
      'utf8',
    );
  }
}
