import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { CONFIG_FILE_NAME, CORYDORA_DIR_NAME, TASK_CATEGORY_FILES } from '../constants.js';
import { parseCorydoraConfig } from './schema.js';
import type { CorydoraConfig, TaskCategory } from '../types/domain.js';

function queueTemplate(category: TaskCategory): string {
  const title = category.charAt(0).toUpperCase() + category.slice(1);
  return [
    `# ${title}`,
    '',
    `Generated by Corydora. This file is rendered from machine state in \`${CORYDORA_DIR_NAME}/state/tasks.json\`.`,
    '',
    '## Tasks',
    '',
  ].join('\n');
}

function envTemplate(): string {
  return [
    '# Corydora local secrets',
    '# Keep this file out of source control.',
    '',
    '# ANTHROPIC_API_KEY=',
    '# OPENAI_API_KEY=',
    '# GOOGLE_API_KEY=',
    '# GEMINI_API_KEY=',
    '# AWS_REGION=us-east-1',
    '# OLLAMA_HOST=http://127.0.0.1:11434',
    '',
  ].join('\n');
}

export function resolveConfigPath(projectRoot: string, configPath?: string): string {
  return configPath ? resolve(projectRoot, configPath) : resolve(projectRoot, CONFIG_FILE_NAME);
}

export async function loadConfig(projectRoot: string, configPath?: string): Promise<CorydoraConfig> {
  const resolvedPath = resolveConfigPath(projectRoot, configPath);
  const raw = await readFile(resolvedPath, 'utf8');
  return parseCorydoraConfig(JSON.parse(raw));
}

export async function saveConfig(projectRoot: string, config: CorydoraConfig): Promise<string> {
  const configPath = resolve(projectRoot, CONFIG_FILE_NAME);
  await mkdir(dirname(configPath), { recursive: true });
  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  return configPath;
}

export async function ensureCorydoraStructure(
  projectRoot: string,
  config: CorydoraConfig
): Promise<void> {
  const directories = [
    config.paths.corydoraDir,
    config.paths.stateDir,
    config.paths.logsDir,
    config.paths.runsDir,
    config.paths.agentsDir,
  ];

  for (const relativeDir of directories) {
    await mkdir(resolve(projectRoot, relativeDir), { recursive: true });
  }

  for (const category of Object.keys(TASK_CATEGORY_FILES) as TaskCategory[]) {
    const queuePath = resolve(projectRoot, config.paths.corydoraDir, TASK_CATEGORY_FILES[category]);
    if (!existsSync(queuePath)) {
      await writeFile(queuePath, `${queueTemplate(category)}\n`, 'utf8');
    }
  }

  const envPath = resolve(projectRoot, config.paths.envFile);
  if (!existsSync(envPath)) {
    await writeFile(envPath, envTemplate(), 'utf8');
  }

  const emptyTasksPath = resolve(projectRoot, config.paths.stateDir, 'tasks.json');
  if (!existsSync(emptyTasksPath)) {
    await writeFile(emptyTasksPath, `${JSON.stringify({ tasks: [] }, null, 2)}\n`, 'utf8');
  }
}

export function resolveStatePath(projectRoot: string, config: CorydoraConfig, fileName: string): string {
  return join(projectRoot, config.paths.stateDir, fileName);
}
